### ISSUE TITLE
Make figures of existing DR15 csv spectra

### ISSUE THREAD

**Issue by kevincovey** [kevincovey/T-Tauri#21]
pick a few sample spectra in the APOGEE_Spectra/Richard/DR15/Spectra Files/Emitters folder on CoveyData, read in their wavelength + flux information, and plot them up to produce a simple visual of each spectrum as it is encoded in the existing CSV files

**Comment by elkhilfeh** [comment]
Done for 5 emitters!

**Comment by elkhilfeh** [comment]
Done for 5 emitters!
